# Generated by Django 5.0.7 on 2024-08-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentformfield",
            name="input_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("textarea", "Textarea"),
                    ("email", "Email"),
                    ("number", "Number"),
                    ("date", "Date"),
                    ("url", "URL"),
                    ("select", "Select"),
                    ("checkbox", "Checkbox"),
                    ("radio", "Radio"),
                    ("password", "Password"),
                ],
                default="text",
                max_length=50,
            ),
        ),
    ]
